{
  "id": "ALBA-2020:1599",
  "summary": "libselinux-python:2.8 bug fix and enhancement update",
  "affected": [
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "libselinux-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.9-2.1.module_el8.5.0+24+f1dacb75"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "libselinux-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.9-2.1.module_el8.4.0+2231+ce72eb5e"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "libselinux-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.9-2.1.module_el8.2.0+6102+8e0466a7"
            }
          ]
        }
      ]
    }
  ],
  "aliases": [],
  "published": "2020-04-28T08:55:18Z",
  "modified": "2020-04-28T08:55:11Z",
  "details": "For detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.",
  "references": [
    {
      "url": "https://errata.almalinux.org/8/ALBA-2020-1599.html",
      "type": "ADVISORY"
    }
  ]
}